# Generated by Django 6.0.3 on 2026-04-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='Pending Review', max_length=20),
        ),
    ]
